using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Luqmit3ishBackend.Models
{
    public class Dish
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // ID column is generated by the database, not manually
        public int Id { get; set; }
        [Required(ErrorMessage = "User id number is required")]
        public int UserId { get; set; }
        public String Name { get; set; }
        public String Description { get; set; }
        public String Type { get; set; }
        public String Photo { get; set; }
        public int KeepValid { get; set; }
        [Required(ErrorMessage = "Dishes number is required")]
        public int Quantity { get; set; }
    }
}
